spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**

        - id: vendor-service
          uri: lb://VENDOR-SERVICE
          predicates:
            - Path=/api/v1/vendors/**

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**

        - id: product-movement-service
          uri: lb://PRODUCT-MOVEMENT-SERVICE
          predicates:
            - Path=/api/v1/product-movements/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**

        - id: order-item-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order-items/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**

        - id: shipment-service
          uri: lb://SHIPMENT-SERVICE
          predicates:
            - Path=/api/v1/shipments/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**


server:
  port: 4400
