spring:
  datasource:
    url: jdbc:postgresql://localhost:6543/payment
    username: romazal
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  kafka:
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring.json.type.mapping: paymentConfirmation:com.romazal.ecommerce.notification.PaymentNotificationRequest
#application:
#  config:
#    product-url: http://localhost:4500/api/v1/products
server:
  port: 4060