spring:
  datasource:
    url: jdbc:postgresql://localhost:6543/product
    username: romazal
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: productThresholdNotification:com.romazal.ecommerce.kafka.ProductThresholdNotification

server:
  port: 4040

application:
  config:
    vendor-url: http://localhost:4030/api/v1/vendors