spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:4000
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: "http://localhost:4444/realms/micro-services"


