package com.romazal.ecommerce.notification;

public enum NotificationType {
    PRODUCT_THRESHOLD_NOTIFICATION,
    ORDER_PAYMENT_LINK_NOTIFICATION,
    ORDER_CONFIRMATION_NOTIFICATION,
    ORDER_CANCELLATION_NOTIFICATION,
    PAYMENT_CONFIRMATION_NOTIFICATION,
    PAYMENT_REFUND_NOTIFICATION,
    SHIPMENT_SHIPPED_NOTIFICATION,
    SHIPMENT_DELIVERED_NOTIFICATION
}
